//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_RCTAN1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=tcp:operaciones1.database.windows.net,1433;Initial Catalog=RcTan1;Persist " +
            "Security Info=False;User ID=Operaciones;Password=114057Tup;MultipleActiveResultS" +
            "ets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;")]
        public string RcTan1ConnectionString {
            get {
                return ((string)(this["RcTan1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=tcp:operaciones1.database.windows.net,1433;Initial Catalog=RcTan1;Persist " +
            "Security Info=False;User ID=Operaciones;Password=114057Tup;MultipleActiveResultS" +
            "ets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;")]
        public string RcTan1ConnectionString1 {
            get {
                return ((string)(this["RcTan1ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=operaciones1.database.windows.net;Initial Catalog=RcTan1;Persist Secu" +
            "rity Info=True;User ID=Operaciones;Password=114057Tup;Encrypt=True;TrustServerCe" +
            "rtificate=False;Connection Timeout=30;")]
        public string RcTan1ConnectionString2 {
            get {
                return ((string)(this["RcTan1ConnectionString2"]));
            }
        }
    }
}
